[manifest]
version = "1.0.0"
dump_lua = true
priority = 422

# code card fallback
[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/code.lua"]'''
pattern = '''default = "c_cry_crash",'''
position = "at"
payload = '''default = "c_cry_oboe",'''
match_indent = true

# profile names
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = 'Cryptid.profile_prefix = "M"'
position = "at"
payload = 'Cryptid.profile_prefix = "J"'
match_indent = true

# tutorial stuff
[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "lib/gameset.lua"]'''
pattern = '''if not G.SETTINGS.paused and not G.PROFILES[G.SETTINGS.profile].cry_intro_complete then'''
position = "before"
payload = '''G.selectedGameset = "madness"
G.PROFILES[G.SETTINGS.profile].cry_intro_complete = true
G.PROFILES[G.SETTINGS.profile].cry_gameset = G.selectedGameset
G.SETTINGS.paused = false
if G.gamesetUI then
    G.gamesetUI:remove()
end
if G.gateway then
    G.gateway:remove()
end
if G.yawetag then
    G.yawetag:remove()
end
G.E_MANAGER:clear_queue("tutorial")
if G.OVERLAY_TUTORIAL then
    G.OVERLAY_TUTORIAL.Jimbo:remove()
    if G.OVERLAY_TUTORIAL.content then
        G.OVERLAY_TUTORIAL.content:remove()
    end
end
'''
match_indent = true


# gateway saint compat
[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/exotic.lua"]'''
pattern = '''return #Cryptid.advanced_find_joker(nil, nil, nil, { "eternal" }, true, "j") < G.jokers.config.card_limit'''
position = "at"
payload = '''		if (#SMODS.find_card("j_jen_saint") + #SMODS.find_card("j_jen_saint_attuned")) > 0 then
			return #G.jokers.cards < G.jokers.config.card_limit
		else
			--Don't allow use if everything is eternal and there is no room
			return #Cryptid.advanced_find_joker(nil, nil, nil, { "eternal" }, true, "j") < G.jokers.config.card_limit
		end'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/exotic.lua"]'''
pattern = '''local deletable_jokers = {}'''
position = "before"
payload = '''if (#SMODS.find_card("j_jen_saint") + #SMODS.find_card("j_jen_saint_attuned")) <= 0 then'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/exotic.lua"]'''
pattern = '''return true
			end,
		}))
		delay(0.6)'''
position = "after"
payload = '''end'''
match_indent = true


# no ghost
[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/spooky.lua"]'''
pattern = '''		--create a ghost
		local card = create_card("Joker", G.jokers, nil, nil, nil, nil, "j_cry_ghost")
		card:add_to_deck()
		G.jokers:emplace(card)'''
position = "at"
payload = '''		--DON'T create a ghost
		if G.GAME.dollars ~= 0 then
            ease_dollars((-G.GAME.dollars - 1e6), true)
        end'''
match_indent = true

# to_big(G.GAME.hands["High Card"].level) <= to_big(7200) and G.C.HAND_LEVELS['!' .. number_format(to_big(G.GAME.hands["High Card"].level))] 
# or G.C.HAND_LEVELS[number_format(to_big(G.GAME.hands["High Card"].level))] or G.C.UI.TEXT_DARK --jen was here



# all of the cryptid planet color things

# timantti
[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/planet.lua"]'''
pattern = '''to_big(G.GAME.hands["High Card"].level) == to_big(1) and G.C.UI.TEXT_DARK
or G.C.HAND_LEVELS[to_big(math.min(7, G.GAME.hands["High Card"].level)):to_number()]'''
position = "at"
payload = '''to_big(G.GAME.hands["High Card"].level) <= to_big(7200) and G.C.HAND_LEVELS["!" .. number_format(to_big(G.GAME.hands["High Card"].level))] 
or G.C.HAND_LEVELS[number_format(to_big(G.GAME.hands["High Card"].level))] or G.C.UI.TEXT_DARK --jen was here'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/planet.lua"]'''
pattern = '''to_big(G.GAME.hands["Pair"].level) == to_big(1) and G.C.UI.TEXT_DARK or G.C.HAND_LEVELS[to_big(
math.min(7, G.GAME.hands["Pair"].level)
):to_number()]'''
position = "at"
payload = '''to_big(G.GAME.hands["Pair"].level) <= to_big(7200) and G.C.HAND_LEVELS["!" .. number_format(to_big(G.GAME.hands["Pair"].level))] 
or G.C.HAND_LEVELS[number_format(to_big(G.GAME.hands["Pair"].level))] or G.C.UI.TEXT_DARK --jen was here'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/planet.lua"]'''
pattern = '''to_big(G.GAME.hands["Two Pair"].level) == to_big(1) and G.C.UI.TEXT_DARK
or G.C.HAND_LEVELS[to_big(math.min(7, G.GAME.hands["Two Pair"].level)):to_number()]'''
position = "at"
payload = '''to_big(G.GAME.hands["Two Pair"].level) <= to_big(7200) and G.C.HAND_LEVELS["!" .. number_format(to_big(G.GAME.hands["Two Pair"].level))] 
or G.C.HAND_LEVELS[number_format(to_big(G.GAME.hands["Two Pair"].level))] or G.C.UI.TEXT_DARK --jen was here'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/planet.lua"]'''
pattern = '''to_big(G.GAME.hands["Three of a Kind"].level) == to_big(1) and G.C.UI.TEXT_DARK
or G.C.HAND_LEVELS[to_big(math.min(7, G.GAME.hands["Three of a Kind"].level)):to_number()]'''
position = "at"
payload = '''to_big(G.GAME.hands["Three of a Kind"].level) <= to_big(7200) and G.C.HAND_LEVELS["!" .. number_format(to_big(G.GAME.hands["Three of a Kind"].level))] 
or G.C.HAND_LEVELS[number_format(to_big(G.GAME.hands["Three of a Kind"].level))] or G.C.UI.TEXT_DARK --jen was here'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/planet.lua"]'''
pattern = '''to_big(G.GAME.hands["Straight"].level) == to_big(1) and G.C.UI.TEXT_DARK
or G.C.HAND_LEVELS[to_big(math.min(7, G.GAME.hands["Straight"].level)):to_number()]'''
position = "at"
payload = '''to_big(G.GAME.hands["Straight"].level) <= to_big(7200) and G.C.HAND_LEVELS["!" .. number_format(to_big(G.GAME.hands["Straight"].level))] 
or G.C.HAND_LEVELS[number_format(to_big(G.GAME.hands["Straight"].level))] or G.C.UI.TEXT_DARK --jen was here'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/planet.lua"]'''
pattern = '''to_big(G.GAME.hands["Flush"].level) == to_big(1) and G.C.UI.TEXT_DARK or G.C.HAND_LEVELS[to_big(
						math.min(7, G.GAME.hands["Flush"].level)
					):to_number()]'''
position = "at"
payload = '''to_big(G.GAME.hands["Flush"].level) <= to_big(7200) and G.C.HAND_LEVELS["!" .. number_format(to_big(G.GAME.hands["Flush"].level))] 
or G.C.HAND_LEVELS[number_format(to_big(G.GAME.hands["Flush"].level))] or G.C.UI.TEXT_DARK --jen was here'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/planet.lua"]'''
pattern = '''to_big(G.GAME.hands["Full House"].level) == to_big(1) and G.C.UI.TEXT_DARK
or G.C.HAND_LEVELS[to_big(math.min(7, G.GAME.hands["Full House"].level)):to_number()]'''
position = "at"
payload = '''to_big(G.GAME.hands["Full House"].level) <= to_big(7200) and G.C.HAND_LEVELS["!" .. number_format(to_big(G.GAME.hands["Full House"].level))] 
or G.C.HAND_LEVELS[number_format(to_big(G.GAME.hands["Full House"].level))] or G.C.UI.TEXT_DARK --jen was here'''
match_indent = true 

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/planet.lua"]'''
pattern = '''to_big(G.GAME.hands["Four of a Kind"].level) == to_big(1) and G.C.UI.TEXT_DARK
or G.C.HAND_LEVELS[to_big(math.min(7, G.GAME.hands["Four of a Kind"].level)):to_number()]'''
position = "at"
payload = '''to_big(G.GAME.hands["Four of a Kind"].level) <= to_big(7200) and G.C.HAND_LEVELS["!" .. number_format(to_big(G.GAME.hands["Four of a Kind"].level))] 
or G.C.HAND_LEVELS[number_format(to_big(G.GAME.hands["Four of a Kind"].level))] or G.C.UI.TEXT_DARK --jen was here'''
match_indent = true 

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/planet.lua"]'''
pattern = '''to_big(G.GAME.hands["Straight Flush"].level) == to_big(1) and G.C.UI.TEXT_DARK
or G.C.HAND_LEVELS[to_big(math.min(7, G.GAME.hands["Straight Flush"].level)):to_number()]'''
position = "at"
payload = '''to_big(G.GAME.hands["Straight Flush"].level) <= to_big(7200) and G.C.HAND_LEVELS["!" .. number_format(to_big(G.GAME.hands["Straight Flush"].level))] 
or G.C.HAND_LEVELS[number_format(to_big(G.GAME.hands["Straight Flush"].level))] or G.C.UI.TEXT_DARK --jen was here'''
match_indent = true 

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/planet.lua"]'''
pattern = '''to_big(G.GAME.hands["Five of a Kind"].level) == to_big(1) and G.C.UI.TEXT_DARK
or G.C.HAND_LEVELS[to_big(math.min(7, G.GAME.hands["Five of a Kind"].level)):to_number()]'''
position = "at"
payload = '''to_big(G.GAME.hands["Five of a Kind"].level) <= to_big(7200) and G.C.HAND_LEVELS["!" .. number_format(to_big(G.GAME.hands["Five of a Kind"].level))] 
or G.C.HAND_LEVELS[number_format(to_big(G.GAME.hands["Five of a Kind"].level))] or G.C.UI.TEXT_DARK --jen was here'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/planet.lua"]'''
pattern = '''to_big(G.GAME.hands["Flush House"].level) == to_big(1) and G.C.UI.TEXT_DARK
or G.C.HAND_LEVELS[to_big(math.min(7, G.GAME.hands["Flush House"].level)):to_number()]'''
position = "at"
payload = '''to_big(G.GAME.hands["Flush House"].level) <= to_big(7200) and G.C.HAND_LEVELS["!" .. number_format(to_big(G.GAME.hands["Flush House"].level))] 
or G.C.HAND_LEVELS[number_format(to_big(G.GAME.hands["Flush House"].level))] or G.C.UI.TEXT_DARK --jen was here'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/planet.lua"]'''
pattern = '''to_big(G.GAME.hands["Flush Five"].level) == to_big(1) and G.C.UI.TEXT_DARK
or G.C.HAND_LEVELS[to_big(math.min(7, G.GAME.hands["Flush Five"].level)):to_number()]'''
position = "at"
payload = '''to_big(G.GAME.hands["Flush Five"].level) <= to_big(7200) and G.C.HAND_LEVELS["!" .. number_format(to_big(G.GAME.hands["Flush Five"].level))] 
or G.C.HAND_LEVELS[number_format(to_big(G.GAME.hands["Flush Five"].level))] or G.C.UI.TEXT_DARK --jen was here'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/planet.lua"]'''
pattern = '''to_big(G.GAME.hands["cry_Bulwark"].level) == to_big(1) and G.C.UI.TEXT_DARK
or G.C.HAND_LEVELS[to_big(math.min(7, G.GAME.hands["cry_Bulwark"].level)):to_number()]'''
position = "at"
payload = '''to_big(G.GAME.hands["cry_Bulwark"].level) <= to_big(7200) and G.C.HAND_LEVELS["!" .. number_format(to_big(G.GAME.hands["cry_Bulwark"].level))] 
or G.C.HAND_LEVELS[number_format(to_big(G.GAME.hands["cry_Bulwark"].level))] or G.C.UI.TEXT_DARK --jen was here'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/planet.lua"]'''
pattern = '''to_big(G.GAME.hands["cry_Clusterfuck"].level) == to_big(1) and G.C.UI.TEXT_DARK
or G.C.HAND_LEVELS[to_big(math.min(7, G.GAME.hands["cry_Clusterfuck"].level)):to_number()]'''
position = "at"
payload = '''to_big(G.GAME.hands["cry_Clusterfuck"].level) <= to_big(7200) and G.C.HAND_LEVELS["!" .. number_format(to_big(G.GAME.hands["cry_Clusterfuck"].level))] 
or G.C.HAND_LEVELS[number_format(to_big(G.GAME.hands["cry_Clusterfuck"].level))] or G.C.UI.TEXT_DARK --jen was here'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/planet.lua"]'''
pattern = '''to_big(G.GAME.hands["cry_UltPair"].level) == to_big(1) and G.C.UI.TEXT_DARK
or G.C.HAND_LEVELS[to_big(math.min(7, G.GAME.hands["cry_UltPair"].level)):to_number()]'''
position = "at"
payload = '''to_big(G.GAME.hands["cry_UltPair"].level) <= to_big(7200) and G.C.HAND_LEVELS["!" .. number_format(to_big(G.GAME.hands["cry_UltPair"].level))] 
or G.C.HAND_LEVELS[number_format(to_big(G.GAME.hands["cry_UltPair"].level))] or G.C.UI.TEXT_DARK --jen was here'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/planet.lua"]'''
pattern = '''to_big(G.GAME.hands["cry_WholeDeck"].level) == to_big(1) and G.C.UI.TEXT_DARK
or G.C.HAND_LEVELS[to_big(math.min(7, G.GAME.hands["cry_WholeDeck"].level)):to_number()]'''
position = "at"
payload = '''to_big(G.GAME.hands["cry_WholeDeck"].level) <= to_big(7200) and G.C.HAND_LEVELS["!" .. number_format(to_big(G.GAME.hands["cry_WholeDeck"].level))] 
or G.C.HAND_LEVELS[number_format(to_big(G.GAME.hands["cry_WholeDeck"].level))] or G.C.UI.TEXT_DARK --jen was here'''
match_indent = true
